name: Run Stock Screener

on:
  workflow_dispatch: # Memungkinkan Anda menjalankan manual
  schedule:
    # Menjalankan setiap 15 menit, dari jam 2 hingga 8 UTC (09:00 - 15:00 WIB)
    # Senin hingga Jumat.
    - cron: '*/15 2-8 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Screener Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python screener_alert.py
